### ISSUE TITLE
OU-XML as a pandoc format

### ISSUE THREAD

**Issue by psychemedia** [pfeifferj/Open-University-Pandoc-Templates#1]
Hi

Do you know if there are any extensions / plugins that support conversion to and from OU-XML via pandoc?

I started looking at an OU-XML2md converter via XSLT (notes [here](https://blog.ouseful.info/2019/11/06/text-publishing-workflows-rooted-on-openlearn-ou-xml-via-github-circleci-and-github-pages/) and [here](https://blog.ouseful.info/2019/11/07/republishing-openlearn-materials-in-markdown-next-step/); I still need to post the XSLT to a repo along with a demo of how to auto-generate the md from OU0XML using it) but it would be much neater to be able to go via pandoc ([related](https://blog.ouseful.info/2019/05/15/quandary-to-pandoc-or-not-yet/)).

Jupyter notebooks / ipynb format is now recognised as a native format by pandoc, so if OU-XML was also supported by pandoc it would make all manner of conversions possible.

**Comment by pfeifferj** [comment]
Hiya, 

In principle, this should be possible. You might get away with just writing a .lua that deals with the OU-XML syntax. I don't think there's anything around at the moment, though.

For more complex syntax, you might need to look into [mmark](https://github.com/mmarkdown/mmark)

**Comment by psychemedia** [comment]
Ok, thanks... lua is still an alien language to me, as are pandoc internals... Could perhaps make for a New Year's resolution for me tho!
